### ISSUE TITLE
cannot read ?

### ISSUE THREAD

**Issue by mightydanp** [LakMoore/InfiniTiC#1]
i made a invar.json file in configs/infinitic  and my material isnt loading.
http://pastebin.com/ZK9QEvZY

**Comment by LakMoore** [comment]
Hey, sorry for the wait.

Instead of:
"blocks": ["gregtech:gt.blockmetal3.11"],
try
"blocks": ["gregtech:gt.blockmetal3:11"],

Separating the meta value from the name with a colon.

I haven't tested it but if that still doesn't work, please also post the log.
