### ISSUE TITLE
[1.12] Could not read or parse json file

### ISSUE THREAD

**Issue by Thyriel** [LakMoore/InfiniTiC#10]
Hi,

i tried your mod in 1.12 and can't get it to work. Created a "diamonds.json" in config/infinitic with copy & paste your "1.10.2 and newer" JSON example. Logfile gives an error: 

> [14:52:47] [main/TRACE] [infinitic/infinitic]: Sending event FMLPreInitializationEvent to mod infinitic
[14:52:47] [main/ERROR] [infinitic/infinitic]: Could not read or parse file 'diamonds.json'

Pasting your example json on jsonlint gives an error too:
`Error: Parse error on line 61:
...chingModifier": 1.0 "__traits_comment": 
-----------------------^
Expecting 'EOF', '}', ',', ']', got 'STRING'`

**Comment by AurySystem** [comment]
There is a comma missing after the "flechingModfier": 1.0 in the example material, which causes it to not parse correctly.

**Comment by LakMoore** [comment]
Good find people!  Fixed the example material in the wiki.  Thank you.
