### ISSUE TITLE
[1.12] Unsmeltable tool parts

### ISSUE THREAD

**Issue by Mike-U5** [LakMoore/InfiniTiC#14]
I'm attempting to make an armor set from a mod a material.
The metal that the armor set is made of has no associated ingot, block, nugget or gem.
So I registered the sword as the ingot instead.

The parts are all showing up in Creative Mode and in JEI, but I am unable to actually smelt any items in the set, even the sword that I registered as ingot.
The liquid does exist, but cheating it into my furnace still leaves be unable to cast any parts from it.

I tried not having an ingot set at all, but that has the same result.
Is there anything I can do to make it work without a "real" ingot?

> {
> 	"name": "Ice",
> 	"make": ["fluid"],
> 	"textColor": "#66B8DA",
> 	"whitelist": {
> 		"oredict": [],
> 		"ingots": [],
> 		"nuggets": [],
> 		"dusts": [],
> 		"gems": [],
> 		"blocks": [],
> 		"ores": []
> 	},
> 	"blacklist": {
> 		"oredict": [],
> 		"ores": []
> 	},
> 	"fluidData": {
> 		"color": "#66B8DA",
> 		"density": 2000,
> 		"viscosity": 10000,
> 		"temperature": 100,
> 		"luminosity": 10,
> 		"rarity": "UNCOMMON"
> 	},
> 	"canCraftToolForge": false,
> 	"toolData": {
> 		"durability": 28,
> 		"harvestLevel": 4,
> 		"extraDurability": 400,
> 		"miningSpeed": 8,
> 		"attack": 7.5,
> 		"handleModifier": 1.25,
> 		"handleDurability": 0,
> 		"color": "#66B8DA",
> 		"temperature": 0,
> 		"projectiles": false,
> 		"drawSpeed": 1.0,
> 		"range": 1.0,
> 		"bonusDamage": 0.0,
> 		"stringModifier": 0.0,
> 		"shaftModifier": 1.0,
> 		"bonusAmmo": 0.0,
> 		"accuracy": 1.0,
> 		"fletchingModifier": 1.0,
>         "traits": ["freezing"],
>         "headTraits": ["freezing"],
>         "handleTraits": [],
>         "extraTraits": [],
>         "bowTraits": [],
>         "stringTraits": [],
>         "projectileTraits": [],
>         "shaftTraits": [],
>         "fletchingTraits": []
> 	},
> 	"localizations": [{
> 		"locale": "en_US",
> 		"solid": "Ice",
> 		"liquid": "Molten Ice",
> 		"bucket": "Ice Bucket"
> 	}]
> }

**Comment by LakMoore** [comment]
I don't think this is going to work....
However, what object will your players throw into the smeltry to melt into your fluid?

**Comment by Mike-U5** [comment]
Oh I use Modtweaker to set those.  
However, changing 
>"ingots": [],   

to   

>"ingots": ["twilightforest:ice_sword"],  

will still result into an unusable liquid.

**Comment by Mike-U5** [comment]
Here is another JSON file that doesn't work as an example. The Json is valid and the liquid and the parts are all generated, but they cannot be made in any way.

> {
> 	"name": "Creativium",
> 	"make": ["fluid"],
> 	"textColor": "#D2F200",
> 	"whitelist": {
> 		"oredict": [],
> 		"ingots": [],
> 		"nuggets": [],
> 		"dusts": [],
> 		"gems": [],
> 		"blocks": ["tconstruct:materials:16"],
> 		"ores": []
> 	},
> 	"blacklist": {
> 		"oredict": [],
> 		"ores": []
> 	},
> 	"fluidData": {
> 		"color": "#D2F200",
> 		"density": 2000,
> 		"viscosity": 10000,
> 		"temperature": 1000,
> 		"luminosity": 10,
> 		"rarity": "RARE"
> 	},
> 	"canCraftToolForge": false,
> 	"toolData": {
> 		"durability": 1600,
> 		"harvestLevel": 8,
> 		"extraDurability": 150,
> 		"miningSpeed": 9,
> 		"attack": 8.25,
> 		"handleModifier": 1.2,
> 		"handleDurability": 0,
> 		"color": "#D2F200",
> 		"temperature": 0,
> 		"projectiles": false,
> 		"drawSpeed": 1.0,
> 		"range": 1.0,
> 		"bonusDamage": 0.0,
> 		"stringModifier": 0.0,
> 		"shaftModifier": 1.0,
> 		"bonusAmmo": 0.0,
> 		"accuracy": 0.0,
> 		"fletchingModifier": 0.0,
>         "traits": ["ecological"],
>         "headTraits": ["alien","insatiable"],
>         "handleTraits": ["cheap", "petramor"],
>         "extraTraits": ["crumbling", "lightweight"],
>         "bowTraits": [],
>         "stringTraits": [],
>         "projectileTraits": [],
>         "shaftTraits": [],
>         "fletchingTraits": []
> 	},
> 	"localizations": [{
> 		"locale": "en_US",
> 		"solid": "Creativium",
> 		"liquid": "Molten Creativium",
> 		"bucket": "Sanctum Creativium"
> 	}]
> }

**Comment by geekkid1** [comment]
I am having the _exact_ same problem with some materials I'm making! I'll see what I can dig up on what _might_ be the problem, but since I'm kind of an amateur here I feel like the dev can do better work at than than I can.

**Comment by geekkid1** [comment]
I think I found something! I believe the problem _may_ lie in using custom items (meaning not from vanilla MC) for the items in the json file. I tested one of my materials, and then tested the standard diamond example, and the diamond smelted properly and everything. So maybe that is the problem.

**Comment by geekkid1** [comment]
I think found a way to make it work! I set items in both blocks and ingots, and it started working properly. Pending on using custom items instead of vanilla ones, but it's looking good so far. I understand this issue is over a year old but I'm still going to post any updates I have here.

**Comment by geekkid1** [comment]
Yeah, that got it working! I added the items from my mod into both the ingots and blocks categories of my `[material].json` and the liquid was usable. I would suggest trying that if you're still paying attention to this issue and you still have that problem.

**Comment by LakMoore** [comment]
Thank you for the feedback.  Also, there is a new version released for MC1.12.2.
