### ISSUE TITLE
Unable to create working JSON files.

### ISSUE THREAD

**Issue by Goht** [LakMoore/InfiniTiC#15]
I'm trying to use the template JSON file to make this file work. (File uploaded as .txt file for github compatibility]
It's in the folder: "minecraft\config\infinitic"
[Diamond.txt](https://github.com/LakMoore/InfiniTiC/files/1383209/Diamond.txt)

I'm not sure why this isn't working. I seem to be following all the instructions; but even the safest code is not working in my build.

This is for version 1.12-0.1.42.

**Comment by Mike-U5** [comment]
This seems to be at least partially related to [my issue](https://github.com/LakMoore/InfiniTiC/issues/14).

**Comment by Goht** [comment]
You seem to have more success. I couldn't even see any items in JEI

**Comment by LakMoore** [comment]
Please can you post a gist of your log?

**Comment by Testure** [comment]
it seems its not a json file

**Comment by LakMoore** [comment]
Closing for now.  Please re-post your JSON file and Minecraft log, if you'd like me to look into the problem further.  Thank you.
