### ISSUE TITLE
All liquids light blue

### ISSUE THREAD

**Issue by theshadowake** [LakMoore/InfiniTiC#2]
I've made 3 materials the parts are the correct color, but the fluid is always the same light blue. Is there any way to specify this color?

**Comment by LakMoore** [comment]
Please can you link to a post of your JSON file?

**Comment by theshadowake** [comment]
I have the following 3:
http://pastebin.com/xQmZ6Cs4
http://pastebin.com/2A3DUP9W
http://pastebin.com/k8HNc3c2

**Comment by LakMoore** [comment]
All fixed!  You need version 0.1.4, which is here: https://minecraft.curseforge.com/projects/infini-tic/files/2355120

Also, please note I have changed the localisation section of the JSON file.  Have also updated the wiki to match and an example is below:

   "localizations": [{
 		"locale": "en_US",
 		"solid": "Lapis",
 		"liquid": "Molten Lapis",
 		"bucket": "Lapis Bucket"
 	}]

Thanks for raising the issue.
