### ISSUE TITLE
TiC items not castable when no input items are defined

### ISSUE THREAD

**Issue by Thyriel** [LakMoore/InfiniTiC#20]
When there is no valid input item defined in the whitelist section, the TiC parts and items are created (shown in JEI and cheatable) but they are all missing a casting recipe.

I know it may not have been your intention using InfiniTic without specifying a valid input item, but as ModTweaker recently readded TiC support it would be a great help if that would work so i can define my own alloys and use InfiniTic just to create the liquid + TiC items without any ore/ingot/block being added.

`"whitelist": {
		"__comment": "Everything in the whitelist will be added to the OreDictionary with the above name.",
		"oredict": [],
		"ingots": [],
		"nuggets": [],
		"dusts": [],
		"gems": [],
		"blocks": [],
		"ores": []
	},`

**Comment by LakMoore** [comment]
I can look into this but one of the required calls to the Tinkers API requires a physical material.  Have you considered how your players would repair their tools in the tool station if no solid item is associated as per your request?

**Comment by Thyriel** [comment]
Good point with the repair. In the meantime i anyway found a way to bypass the metadata problem in #21 which also solved this issue for me:
- Using Romimocos ore mod i added dummy ingots (with similar itemname so it works, see #21 bug 2nd comment) that i specified in whitelist input (ore nit generated)
- With Modtweaker i then removed the TiC smelting from those dummy ingots and added smelting from the real ingots (e.g. Botanias Elementium, Gaia Spirit) and blocks.

So as i needed anyway to add custom ingots i then just added ingots and blocks for my own alloys too.
So if you say this isn't doable anyway because of TiC restrictions i think this issue can be closed.

**Comment by Mike-U5** [comment]
Could you not use shards cast shards out of that material and use those to repair your tools?
You'd have to add a way to smelt thise though.

**Comment by Mike-U5** [comment]
You could repair stuff with shards, if you add a way to cast those.

**Comment by Thyriel** [comment]
@Mike-U5  i added ingots then with another mod so the tools should be repairable now ;)

**Comment by LakMoore** [comment]
If you add ingots with another mod then you should be able to add that ingot to the ingot whitelist.  Then Infini-TiC has a solid and it should all work nicely.

The shard idea is how Tinker's deals with repairing materials without ingots.  Shards should always be cast-able or craft-able for any material.
