### ISSUE TITLE
Crash when starting game

### ISSUE THREAD

**Issue by CobaltRealm** [LakMoore/InfiniTiC#24]
I'm playing in 1.12.2 and have created 6 materials with the mod

link to the crash: https://pastebin.com/5yHWVVHU

**Comment by RadicalBean** [comment]
I had the same issue and after a bit of troubleshooting I found out downgrading infini-tic to 0.1.35 which is marked as 0.1.36 on the curseforge page for some reason made it work again

**Comment by CobaltRealm** [comment]
Really? I will try it, also I think this has to do with Insane96 mods since I created only 3 materials with Carbonado, Vulcanite, and Galaxite (materials from his mods) and it crashes the game but when I create another material it works (maybe it's another bug, I'm no really sure)

**Comment by RadicalBean** [comment]
I havent created any materials but I got the same error code as you, it didnt matter what combination of the newer version of infini-tic I was using with what version of tconstruct, eventually downgrading fixed it (for me)

**Comment by CobaltRealm** [comment]
Ok thanks

**Comment by RadicalBean** [comment]
#12 
Reviving this issue, after doing a bit of looking at the code it seems that the issue is caused by an error in a .json with a gem attached.
Would you mind posting your JSON files?

**Comment by CobaltRealm** [comment]
Ok, right now I can't post them but I'll try to get them here as soon as I can

**Comment by RadicalBean** [comment]
Thanks a lot, after doing some more testing im like 99% sure that it's a bug with the registering of gems for material use.
Which I sadly dont know how to fix because I cant code at all

**Comment by CobaltRealm** [comment]
Hey!

here's the link to the json

https://pastebin.com/Jij4QXyt

**Comment by RadicalBean** [comment]
Well, that confirms it.
Adding anything with a gem breaks Infini-TIC
what a shame :(

**Comment by LakMoore** [comment]
I'll take a look at working with Gems.

**Comment by LakMoore** [comment]
New version released for MC1.12.2.  This should work correctly now.  If not, please post a link to the mod you are using and a pastebin of your json config file.
