### ISSUE TITLE
Cant use gems/ingots from my mod

### ISSUE THREAD

**Issue by Testure** [LakMoore/InfiniTiC#26]
so i have every thing working my metal is in the game and i can make the tools but you cant smelt the raw metal in the smeltery, and it only does this with stuff from my mod if i use say diamonds it works.

**Comment by Testure** [comment]
i found out that this only happens when a invaild item is entered as ingot or gem but i am entering my items internal name(witch is the name that /it hand gives me) and this still happens

**Comment by Arkimu** [comment]
Yeah same problem, and it was already reported [HERE] (https://github.com/LakMoore/InfiniTiC/issues/24), It seems, saddly that it won't go anywhere.

Try and downgrade as RadicalBean said.

**Comment by LakMoore** [comment]
New version released for MC1.12.2.  This should work correctly now.  If not, please post a link to the mod you are using and a pastebin of your json config file.
