### ISSUE TITLE
[1.12.2] Crash on Start Up

### ISSUE THREAD

**Issue by Draskh** [LakMoore/InfiniTiC#27]
[crash-2018-06-06_17.40.44-client.txt](https://github.com/LakMoore/InfiniTiC/files/2077024/crash-2018-06-06_17.40.44-client.txt)

**Comment by LakMoore** [comment]
Thank you for the bug report.  If you could post the JSON file for your materials and a copy of the Minecraft log from startup to crash, then I will be able to investigate further.  Thank you.

**Comment by Draskh** [comment]
I haven't the .json anymore.
