### ISSUE TITLE
Gem handling

### ISSUE THREAD

**Issue by theshadowake** [LakMoore/InfiniTiC#3]
Would it be/is it possibe to handle gems?

E.g pour out into gem cast if ore dict is gemXXX for example?

**Comment by LakMoore** [comment]
That would be good, wouldn't it.  I believe this would be possible and will get it added ASAP.

**Comment by theshadowake** [comment]
👍 Would be super usefull thanks.

**Comment by LakMoore** [comment]
I have added this to version 0.1.6, which is available for MC 1.8.9!!
