### ISSUE TITLE
Feature Request - Updated to 1.10.2!

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [LakMoore/InfiniTiC#4]
@LakMoore 
If you are having issues getting started contact this mod author and ask modding questions! Just try and be patient as he tends to do a lot at a time. If you need help go to his discord located here https://discord.gg/WYG7zjJ

* THIS IS NOT FOR OTHER USERS ONLY THE CREATOR OF INIFINTIC *

**Comment by majix560** [comment]
You linked Thut's discord, not LakMoore's.

**Comment by P3rf3ctXZer0** [comment]
Please don't contact me the message was for the creator of this mod not you @majix560

**Comment by GazbonicAcid** [comment]
@P3rf3ctXZer0 what I don't like is that after Thut told you not to suggest to @LakMoore to contact him, you edited the issue but left the suggestion in.
Although I full-heartedly agree that this mod needs to be updated to 1.10.2

**Comment by LakMoore** [comment]
Not sure what is going on up there ^^^ but I can say that I have no current plans to update this 1.10.2.

I would like to do so but have no time to complete the work.  If someone wants to fork this git and either do the work or make a start that is fine and I may even chip in but I don't want to get your hopes up for me to do it any time soon.  Sorry.
