### ISSUE TITLE
[1.10.2] Fluids render complete black

### ISSUE THREAD

**Issue by heidrifx** [LakMoore/InfiniTiC#6]
For every new material I add the liquid block just renders black. The only thing that seems to change is the alpha value, any changed rgb value just gets ignored.
However, the fluid renders as expected inside Smeltery, Pipes and Basin/Table (with the correct color).

Link to JSON file: https://pastebin.com/vCi6wAhq

Fluid renders as expected inside the Smeltery:
<img width="1440" alt="fluid in smeltry" src="https://user-images.githubusercontent.com/8414127/30271420-81958b2e-96f0-11e7-8cb4-7ca572e1587b.png">

Fluid is complete black when placed in the world:
<img width="1440" alt="fluid in world" src="https://user-images.githubusercontent.com/8414127/30271422-81b9b3b4-96f0-11e7-9767-7eefa21bbcc0.png">

**Comment by LakMoore** [comment]
Please will you re-test with the latest version for 1.10.2, which is 0.1.39.

**Comment by heidrifx** [comment]
Sadly the issue still occurs in the latest version 0.1.39.

**Comment by LakMoore** [comment]
I can confirm that I can re-produce this problem but at this time I am at a total loss as to the cause.  The same code works correctly on 1.11.2 and 1.12.  I will keep looking as I have time, but if anyone has any ideas or a PR, I'd be very grateful!

**Comment by LakMoore** [comment]
Found it! Fixed it.  The change is published in version 0.1.40.

**Comment by heidrifx** [comment]
Wonderful! May I ask what caused the problem?

**Comment by LakMoore** [comment]
The VertexFormat of the model changed from one version to the next and I was using the wrong format!
