### ISSUE TITLE
[1.7.10] File isn't working. Possible file structure is incorrect?

### ISSUE THREAD

**Issue by aking4125** [LakMoore/InfiniTiC#8]
[Log and Json file.zip](https://github.com/LakMoore/InfiniTiC/files/1309891/Log.and.Json.file.zip)

I tried creating a Json file for the DivineRPG Rupee Ingot to be used as Tinkers tools using this mod following the instructions and the structure of the example file. I don't see anything in that log file (Which is the only Log file it generates unless I'm missing something), and none of the tools or items appear in game and you cannot add the ingots, blocks, ore or dust into the Smeltery to melt them either. I also didn't really understand most of the Data values from the reference either.

**Comment by LakMoore** [comment]
While there is no warning in the log, your JSON contains an error.
Line 67 reads
`"color": "#1796ff"`
but should be
`"color": "#1796ff",`
(note the comma on the end)
