### ISSUE TITLE
1.11.2 Server crash on loading

### ISSUE THREAD

**Issue by Wizardon777** [LakMoore/InfiniTiC#9]
**Minecraft Version:** 1.11.2
**Forge Version:** 13.20.1.2454
**Mod Version:** InfiniTiC-1.11.2-0.1.37

**Crash Report:**
[crash-2017-09-18_18.33.21-server.txt](https://github.com/LakMoore/InfiniTiC/files/1311260/crash-2017-09-18_18.33.21-server.txt)

**More Information:**
Client is working well with mod, only server crash on start.
After removal of mod, Server starts normally.

**Comment by LakMoore** [comment]
This is fixed as per version 0.1.41
